config/routes.rb
Gallery::Application.routes.draw do

  devise_for :users
match  'tags/:tag', :to => 'photos#index' , :as => 'tag'
  resources :albums do
    resources :photos
  end
  resources :photos
  get "home/index"

   root :to => 'home#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :thumb, :user_id
  validates :name, :presence => true
belongs_to :user
has_many :photos

has_attached_file :thumb, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment :thumb,
  :content_type => { :content_type => ['image/jpeg', 'image/png', 'image/gif'] },
  :size => { :in => 0..10.megabytes }
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :album
  attr_accessible :image, :tag_list
  acts_as_taggable
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment :image, :presence => true,
  :content_type => { :content_type => ['image/jpeg', 'image/png', 'image/gif'] },
  :size => { :in => 0..10.megabytes }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_many :albums
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
   
    def index
      @album = current_user.albums.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @album }
        end
    end
    
    
    def new
      @album = Album.new
      
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @album }
        end
    end
    
    
    def create
      @album = current_user.albums.new(params[:album])

     respond_to do |format|
          if @album.save
            format.html { redirect_to @album, :notice => 'Album was successfully created.' }
            format.json { render :json => @album, :status => :created, :location => @album }
          else
            format.html { render :action => "new" }
            format.json { render :json => @album.errors, :status => :unprocessable_entity }
          end
        end
     end
  
 
    def show
      debugger
           @album = Album.find(params[:id])
      respond_to do |format|
         format.html 
         format.json { render :json => @album }
        end
    end
=begin  
    def show
      
      @album = Album.find(params[:id])

      respond_to do |format|
       format.html # show.html.erb
        format.json { render :json => @album }
       end
    end
=end  
    
    
    def edit
      @album = Album.find(params[:id])
    end
  
  
    def update
       @album = Album.find(params[:id])

       respond_to do |format|
           if @album.update_attributes(params[:album])
             format.html { redirect_to @album, :notice => 'Album was successfully updated.' }
             format.json { head :no_content }
           else
             format.html { render :action => "edit" }
             format.json { render :json => @album.errors, :status => :unprocessable_entity }
           end
          end
    end


     def destroy
          @album = Album.find(params[:id])
           @album.destroy

       respond_to do |format|
         format.html { redirect_to albums_url }
         format.json { head :no_content }
       end          
     end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
 before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

    def create
    @album = Album.find(params[:album_id])
    @photo = @album.photos.create(params[:photo])
    redirect_to album_path(@album)
  end


    def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @photo }
    end
  end
          def index
        if params[:tag]
          @photos=Photo.tagged_with(params[:tag])
           respond_to do |format|
         format.html 
     end
 end
 end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_form.html.erb
<%= form_for @album,  :html => { :multipart => true } do |album_form| %>
  <% if @album.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@album.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @album.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= album_form.label :name %><br />
    <%= album_form.text_field :name %>
  </div>
  
  <br>
   <div class="actions">
    <%= album_form.submit  %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>
<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing Albums</h1>
<hr>
<br>
<table cellpadding="15">
<tr>
<% @album.each do |album| %>
		<td>
			<table>	
			<tr>
				<td><%= link_to ((image_tag (album.photos[0].image.url(:medium)),{:size =>"100x100"}), album)unless album.photos[0].nil?  %>
			<!-- <td><%= link_to (image_tag (album.thumb.url(:medium)),{:size =>"30x30"}), album.thumb.url  %></td>
	    	<td><%= link_to 'Show', album %></td>/-->
				</td>
			</tr>
		
			<tr>
				<td> <b><%= link_to (album.name), album %></b> </td>
				
			</tr>
			
			<td><%= link_to 'Edit', edit_album_path(album) %>
    	<%= link_to 'Destroy', album, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
		
		</tr>
		</table>
		</td>
<%end%>
</tr>
</table>
<br>
<%= link_to 'New Album', new_album_path %>
<!--
<table border="1" cellpadding="10">
	<tr>
		<th>Name</th>
		<th>Thumbnail</th>
		<th></th>
		<th></th>
	</tr>
	
<% @album.each do |album| %>
	<tr>
		<td><%= album.name %></td>
		<td><%= link_to ((image_tag (album.photos[0].image.url(:medium)),{:size =>"50x50"}), album)unless album.photos[0].nil?  %></td>
		<td><%= link_to 'Edit', edit_album_path(album) %></td>
    	<td><%= link_to 'Destroy', album, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
	</tr>
	
<%end%>
</table>
-->

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<!--<p id="notice"><%= notice %></p>
<%= image_tag @album.thumb.url(:thumb) %>
-->
<p>
  <font size="6"><b>Album:</b></font>
  <font size="6"><%= @album.name %></font>
</p>  
<hr>
<br>

<table cellpadding="10">
   <tr>
   <% @album.photos.each do |photo| %>
 		
  			
   			<td>
   				<table>
   				<tr>
   					<td><%= link_to (image_tag (photo.image.url(:medium)),{:size =>"100x100"}), photo.image.url  %></td></tr>
				<tr><td>Tags: <%= raw photo.tag_list.map {|t| link_to t, tag_path(t)}.join(', ') %></td></tr>
				</table>
			</td>	
				
		
	<% end %>
  </tr>	
</table>
<%= render "photos/upload" %>
<br>
<br>
<br>
<%= link_to 'Edit Album', edit_album_path(@album) %> |
<%= link_to 'Back to Albums', albums_path %> |

app/views/home/index.html.erb
<h1>Gallery</h1>
<br>
<h3><%= link_to "Albums", albums_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<!--<body background="/images/black.jpg">-->
<body style="background: url(/images/soft.jpg); background-size: 100%;">
 <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
<div id="user_nav" align= "right" float="top">
<% if user_signed_in? %>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
 <% end %>
 </div>
<%= yield %>
  

</body>
</html>

app/views/photos/_upload.html.erb
<%=  form_for ([@album, @album.photos.build]) do |photo_form| %>
  
  <div class = "field">
  <%= photo_form.file_field :image %>
  </div>
  <div class="field">
    <%= photo_form.label :tag_list, 'Tags (seperated by commas)' %><br />
    <%= photo_form.text_field :tag_list %>
  </div>
  <br>
   <div class="actions">
    <%= photo_form.submit 'Upload'%>
	
  </div>
<% end %>

app/views/photos/index.html.erb
<% @photos.each do |photo| %>
 		
  			
   			<td>
   				<table>
   				<tr>
   					<td><%= image_tag (photo.image.url(:medium)),{:size =>"100x100"} %></td></tr>
				<tr><td>Tags: <%= raw photo.tag_list.map {|t| link_to t, tag_path(t)}.join(', ') %></td></tr>
				</table>
			</td>	
				
		
	<% end %>

app/views/photos/show.html.erb
<% @photos.each do |photo| %>
 		
  			
   			<td>
   				<table>
   				<tr>
   					<td><%= image_tag (photo.image.url(:medium)),{:size =>"100x100"} %></td></tr>
				<tr><td>Tags: <%= raw photo.tag_list.map {|t| link_to t, tag_path(t)}.join(', ') %></td></tr>
				</table>
			</td>	
				
		
	<% end %>